### PR TITLE
Meta name author auto detection

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
Because it is [standard stuff](https://www.w3.org/TR/html5/document-metadata.html#standard-metadata-names), I think it's a good idea to add that to the auto detection feature through the `<meta name="author" content="Mario">` tag.
Have a nice day.

### CODE REVIEW

**Comment by Simounet** [comment]
Done.

**Comment by j0k3r** [comment]
Could you check for the failing test?

**Comment by Simounet** [comment]
I checked but there is more than one problem about things I didn't changed. :/

**Comment by j0k3r** [comment]
Looks like it's the new test which fail, not a new one.
https://travis-ci.org/j0k3r/graby/jobs/436707931#L558

Also, I've rebased your branch and fixed an unrelated test on the go.

**Pull request merged**
