### PR TITLE
Convert date to a known format

### PR DESCRIPTION
**Pull request by j0k3r**
Instead of just validating the date is ok when parsing it, just convert it to the W3C format

### CODE REVIEW

**Comment by jtojnar** [comment]
Why not just make `validateDate` return `?DateTime`?

**Comment by j0k3r** [comment]
@jtojnar because it'll break compatibility with current date return. Today we return a plain text which is a valid date according to `parse_date` function. Now it'll return a formatted date instead but it'll still be a string.

**Comment by tcitworld** [comment]
`DateTimeInterface` ? Available since PHP 7.2. Looks odd.

**Comment by j0k3r** [comment]
Nope, it's only the constant that are move to `DateTimeInterface` in PHP 7.2, before that they were defined in `DateTime`:

> 7.2.0 | The class constants of DateTime are now defined on DateTimeInterface.

**Pull request merged**
