### PR TITLE
Handle Safecurl

### LINKED ISSUE #7: Server Side Request Forgery (SSRF)
As [reported with wallabag](https://github.com/wallabag/wallabag/issues/1364#issuecomment-132507674), graby is vulnerable to SSRF. This means one can bypass restrictions for resources only accessible to localhost like  `http://127.0.0.1/server-status`,

### PR DESCRIPTION
**Pull request by j0k3r**
Should fix #7.

@freddyb Are you ok with that patch ?

### CODE REVIEW

**Comment by freddyb** [comment]
I must admit that I don't understand enough of Graby to say with full confidence that this is correct.
If you could provide a smoke-test so a tester can throw URLs at Graby, like [DOMPurify does](https://cure53.de/purify), I would give it a test.

**Comment by j0k3r** [comment]
All right, I've setup a dummy script that took the url given in parameter and give it to graby: http://kimtrip.net/graby/test.php?url=

```php
<?php

require 'vendor/autoload.php';

$graby = new \Graby\Graby(array('debug' => true));

try {
    $res = $graby->fetchContent($_GET['url']);
    var_dump($res);
} catch (\Exception $e) {
    var_dump($e);
}
```

**Comment by freddyb** [comment]
Thanks! Taking a look.

**Comment by freddyb** [comment]
I did some tests on SafeCurl in the meantime, looks good.

**Comment by j0k3r** [comment]
So I guess that if you found SafeCurl good, my integration should be fine too.
Did you find time to take a look using the test url I provided?

**Comment by freddyb** [comment]
Yeah, I did a cursory test to see this is showing similar results as the safecurl testbed at http://safecurl.fin1te.net/

Looks good.

**Comment by j0k3r** [comment]
@freddyb great thanks !

**Pull request merged**
