### PR TITLE
Logger infos added for JsonLd parsing

### PR DESCRIPTION
**Pull request by Simounet**
Hi there,
I added some info from the logger to get debug on JsonLd parsing.
Have a nice day.

### CODE REVIEW

**Comment by j0k3r** [comment]
You should update tests too

**Comment by Simounet** [comment]
Hmm, I'm kind of lost. I've just added logger infos. What do you want me to test?

**Comment by jtojnar** [comment]
Some tests check the log output so you might need to update them.

But first you should fix the undefined member access:

```
Undefined property: Graby\Extractor\ContentExtractor::$author
/home/travis/build/j0k3r/graby/src/Extractor/ContentExtractor.php:1204
/home/travis/build/j0k3r/graby/src/Extractor/ContentExtractor.php:313
/home/travis/build/j0k3r/graby/src/Graby.php:345
/home/travis/build/j0k3r/graby/src/Graby.php:168
/home/travis/build/j0k3r/graby/tests/GrabyTest.php:1617
```

**Comment by Simounet** [comment]
I fixed it. Sorry for that.

**Pull request merged**
